### ISSUE TITLE
Add to pypi repo plz

### ISSUE THREAD

**Issue by vxbinaca** [FullNitrous/NWShell#1]
Fancy website, no python repo presence.

Neat concept though.

**Comment by FullNitrous** [comment]
But this is a program not library

**Comment by FullNitrous** [comment]
I added it to the repo but there seems to be an installation issue. I'll try to fix it.

**Comment by FullNitrous** [comment]
So, now it's added to the repo. You can install it by typing `pip3 install nwshell`.

**Comment by vxbinaca** [comment]
thanks. I maintain a binary (thats also a library) that's on pip.
